### ISSUE TITLE
Page fails load when jumping from another page that did not finish loading

### ISSUE THREAD

**Issue by wei-enwang** [sibyl-dev/sibylapp2#82]
When we tried to switch tabs before the current tab finished running, the new tab did not display any running wheel except the running icon on the top right.

**Comment by zyteka** [comment]
Experimented with this a bit, it looks like the page you've switched to will load correctly once the previous tab finishes loading. Currently, the runtime of similar cases is so long for the full brakepad dataset that it effectively (but not actually) crashes the app.

Probably the best (and possibly only) way to fix this is to speed up the similar cases loading time

**Comment by zyteka** [comment]
Going to deprioritize this for now in favor of focusing on speeding up nearest neighbors from the Pyreal side (https://github.com/sibyl-dev/pyreal/issues/503, https://github.com/sibyl-dev/pyreal/issues/505), but will leave the issue open in case we want to look for a more direct fix later

**Comment by wei-enwang** [comment]
Mark issue as closed since switching to other pages now runs successfully without finish loading the previous page.
